import { Category, Product } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  { id: 1, name: "Shirts & Tops", icon: "👕", productCount: 5 },
  { id: 2, name: "Pants & Jeans", icon: "👖", productCount: 4 },
  { id: 3, name: "Shoes", icon: "👟", productCount: 4 },
  { id: 4, name: "Dresses", icon: "👗", productCount: 3 },
  { id: 5, name: "Jackets & Coats", icon: "🧥", productCount: 3 },
];

export const INITIAL_PRODUCTS: Record<number, Product[]> = {
  1: [
    {
      id: 1,
      name: "White Cotton T-Shirt",
      description: "Comfortable everyday white tee",
      size: "M",
      brand: "Uniqlo",
      color: "White",
      attachments: ["/images/product1.png"],
      categoryId: 1,
    },
    {
      id: 2,
      name: "Navy Blue Button-Up Shirt",
      description: "Formal navy blue dress shirt",
      size: "L",
      brand: "H&M",
      color: "Navy Blue",
      attachments: ["/images/product1.png"],
      categoryId: 1,
    },
    {
      id: 3,
      name: "Striped Long Sleeve",
      description: "Black and white striped casual top",
      size: "M",
      brand: "Zara",
      color: "Black/White",
      attachments: ["/images/product1.png"],
      categoryId: 1,
    },
    {
      id: 4,
      name: "Red Polo Shirt",
      description: "Classic red polo for casual wear",
      size: "L",
      brand: "Ralph Lauren",
      color: "Red",
      attachments: ["/images/product1.png"],
      categoryId: 1,
    },
    {
      id: 5,
      name: "Black Tank Top",
      description: "Simple black sleeveless top",
      size: "S",
      brand: "Forever 21",
      color: "Black",
      attachments: ["/images/product1.png"],
      categoryId: 1,
    },
  ],
  2: [
    {
      id: 6,
      name: "Dark Blue Jeans",
      description: "Classic fit dark wash jeans",
      size: "32W x 30L",
      brand: "Levi's",
      color: "Dark Blue",
      attachments: ["/images/product1.png"],
      categoryId: 2,
    },
    {
      id: 7,
      name: "Black Dress Pants",
      description: "Formal black trousers",
      size: "32W x 32L",
      brand: "Express",
      color: "Black",
      attachments: ["/images/product1.png"],
      categoryId: 2,
    },
    {
      id: 8,
      name: "Khaki Chinos",
      description: "Casual khaki colored chinos",
      size: "34W x 30L",
      brand: "Dockers",
      color: "Khaki",
      attachments: ["/images/product1.png"],
      categoryId: 2,
    },
    {
      id: 9,
      name: "Light Blue Jeans",
      description: "Relaxed fit light wash jeans",
      size: "32W x 30L",
      brand: "Gap",
      color: "Light Blue",
      attachments: ["/images/product1.png"],
      categoryId: 2,
    },
  ],
  3: [
    {
      id: 10,
      name: "White Sneakers",
      description: "Clean white athletic shoes",
      size: "10",
      brand: "Nike",
      color: "White",
      attachments: ["/images/product1.png"],
      categoryId: 3,
    },
    {
      id: 11,
      name: "Black Dress Shoes",
      description: "Formal leather dress shoes",
      size: "9.5",
      brand: "Cole Haan",
      color: "Black",
      attachments: ["/images/product1.png"],
      categoryId: 3,
    },
    {
      id: 12,
      name: "Brown Boots",
      description: "Casual brown leather boots",
      size: "10",
      brand: "Timberland",
      color: "Brown",
      attachments: [],
      categoryId: 3,
    },
    {
      id: 13,
      name: "Running Shoes",
      description: "Athletic running sneakers",
      size: "10",
      brand: "Adidas",
      color: "Gray/Blue",
      attachments: ["running-shoes.jpg"],
      categoryId: 3,
    },
  ],
  4: [
    {
      id: 14,
      name: "Little Black Dress",
      description: "Classic elegant black dress",
      size: "M",
      brand: "Banana Republic",
      color: "Black",
      attachments: ["black-dress.jpg"],
      categoryId: 4,
    },
    {
      id: 15,
      name: "Floral Summer Dress",
      description: "Light floral print sundress",
      size: "S",
      brand: "Target",
      color: "Floral Print",
      attachments: ["floral-dress.jpg"],
      categoryId: 4,
    },
    {
      id: 16,
      name: "Red Evening Gown",
      description: "Formal red evening dress",
      size: "M",
      brand: "BCBG",
      color: "Red",
      attachments: [],
      categoryId: 4,
    },
  ],
  5: [
    {
      id: 17,
      name: "Denim Jacket",
      description: "Classic blue denim jacket",
      size: "L",
      brand: "Levi's",
      color: "Blue",
      attachments: ["denim-jacket.jpg"],
      categoryId: 5,
    },
    {
      id: 18,
      name: "Winter Coat",
      description: "Warm black winter coat",
      size: "M",
      brand: "North Face",
      color: "Black",
      attachments: ["winter-coat.jpg"],
      categoryId: 5,
    },
    {
      id: 19,
      name: "Leather Jacket",
      description: "Black leather motorcycle jacket",
      size: "L",
      brand: "AllSaints",
      color: "Black",
      attachments: [],
      categoryId: 5,
    },
  ],
};
